#ifndef TopParserToken_H
#define TopParserToken_H


#define	T_PROCEDURE	279
#define	T_ID	280
#define	T_END	281
#define	T_ACCESSLOCIRINTERFACE	282
#define	T_ALIASIRINTERFACE	283
#define	T_SIDEEFFECTIRINTERFACE	284
#define	T_CALLGRAPHIRINTERFACE	285
#define	T_CALLGRAPHDFPROBLEMIRINTERFACE	286
#define	T_DEPIRINTERFACE	287

#endif

